/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaregistroanimales;
import java.util.LinkedList;
import java.util.List;

class Animal
{
    String Nombre;
    String TipoHabitad;
    String TipoAlimento;

    public Animal(String Nombre, String TipoHabitad, String TipoAlimento) {
        this.Nombre = Nombre;
        this.TipoHabitad = TipoHabitad;
        this.TipoAlimento = TipoAlimento;
    }

    public String getNombre() {
        return Nombre;
    }

    public String getTipoHabitad() {
        return TipoHabitad;
    }

    public String getTipoAlimento() {
        return TipoAlimento;
    }
    
}

class Aves  extends Animal
{
    String TipoAlas;
    String TipoPico;
    int NumeroExtremidades;

    public Aves(String Nombre, String TipoHabitad, String TipoAlimento, String TipoAlas, String TipoPico, int NumeroExtremidades) {
        super(Nombre, TipoHabitad, TipoAlimento);
        this.TipoAlas = TipoAlas;
        this.TipoPico = TipoPico;
        this.NumeroExtremidades = NumeroExtremidades;
    }

    public String getTipoAlas() {
        return TipoAlas;
    }

    public String getTipoPico() {
        return TipoPico;
    }

    public int getNumeroExtremidades() {
        return NumeroExtremidades;
    }
    
    public String MostrarDatos(){
        return "Nombre: " + getNombre() + "" + "\n"+
                "Tipo de habitad: " + getTipoHabitad() +""+"\n"+
                "Tipo de alimento: " + getTipoAlimento()+""+"\n"+
                "Tipo de alas: " + getTipoAlas()+""+"\n"+
                "Tipo de pico: " + getTipoPico()+""+"\n"+
                "Numero de extremidades: " + getNumeroExtremidades()+""+"\n";
    }
    
}

class Peces extends Animal
{
    int NumeroAletas;
    String TipoEsqueleto;

    public Peces(String Nombre, String TipoHabitad, String TipoAlimento, int NumeroAletas, String TipoEsqueleto) {
        super(Nombre, TipoHabitad, TipoAlimento);
        this.NumeroAletas = NumeroAletas;
        this.TipoEsqueleto = TipoEsqueleto;
    }

    public int getNumeroAletas() {
        return NumeroAletas;
    }

    public String getTipoEsqueleto() {
        return TipoEsqueleto;
    }
    
    public String MostrarDato(){
        return "Nombre: " + getNombre() + "" + "\n"+
                "Tipo de habitad: " + getTipoHabitad() +""+"\n"+
                "Tipo de alimento: " + getTipoAlimento()+""+"\n"+
                "Numero de aletas: " + getNumeroAletas()+""+"\n"+
                "Tipo de esqueleto: " + getTipoEsqueleto()+""+"\n";
    }    
}
public class Menu extends javax.swing.JFrame {
    List<Animal> datos = new LinkedList<>();

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroup1.add(jrba);
        buttonGroup1.add(jrbp);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }
    
    public void Limpiar()
    {
        jtxtNombre.setText("");
        jtxtTipoAlimento.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtTipoAlimento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jsExtremidades = new javax.swing.JSpinner();
        jcbTipoPico = new javax.swing.JComboBox();
        jcbTipoAlas = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jsAletas = new javax.swing.JSpinner();
        jcbEsqueleto = new javax.swing.JComboBox();
        jrba = new javax.swing.JRadioButton();
        jrbp = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        VerDatos = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jcbHabitad = new javax.swing.JComboBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        jLabel2.setText("Tipo de habitad ");

        jLabel3.setText("Tipo de alimento");

        jLabel4.setText("Sistema registro de animales");

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel5.setText("Tipo de alas");

        jLabel6.setText("Tipo de pico");

        jLabel7.setText("Numero de extremidades");

        jcbTipoPico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comedor de semillas", "Pescador", "Insectivoro", "Granivoro", "Carroñero", "Pico-bolsa" }));

        jcbTipoAlas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alas elipticas", "Alas de alta velovidad", "Alas de planeo", "Alas elevadoras" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsExtremidades)
                    .addComponent(jcbTipoPico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTipoAlas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTipoAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTipoPico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jsExtremidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "card2");

        jLabel8.setText("Numero de aletas");

        jLabel9.setText("Tipo de esqueleto");

        jcbEsqueleto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "óseo", "Cartilaginoso" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsAletas)
                    .addComponent(jcbEsqueleto, 0, 113, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jsAletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbEsqueleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "card3");

        jrba.setText("Aves");
        jrba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbaActionPerformed(evt);
            }
        });

        jrbp.setText("Peces");
        jrbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbpActionPerformed(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        VerDatos.setEditable(false);
        VerDatos.setColumns(20);
        VerDatos.setRows(5);
        jScrollPane2.setViewportView(VerDatos);

        jLabel11.setText("Datos ingresados");

        jcbHabitad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acuatico", "Aereo" }));

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jrba)
                    .addComponent(jrbp))
                .addGap(28, 28, 28)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistroLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtTipoAlimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(jtxtNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addComponent(jcbHabitad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbHabitad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtTipoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistroLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jrba)
                                .addGap(18, 18, 18)
                                .addComponent(jrbp))
                            .addGroup(RegistroLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mark.png"))); // NOI18N
        jMenuItem1.setText("Regitrso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbaActionPerformed
        // TODO add your handling code here:
        if(jrba.isSelected())
        {
            jPanel1.setVisible(true);
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
        }
    }//GEN-LAST:event_jrbaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jrba.isSelected())
        {
            Aves as = new Aves(jtxtNombre.getText(), jcbHabitad.getSelectedItem().toString(), jtxtTipoAlimento.getText(), jcbTipoAlas.getSelectedItem().toString(), jcbTipoPico.getSelectedItem().toString(), Integer.parseInt(jsExtremidades.getValue().toString()));
            VerDatos.setText(VerDatos.getText() + "\n\n" + as.MostrarDatos());
            datos.add(as);
            
            Limpiar();            
        }
        else if(jrbp.isSelected())
        {
            Peces ps = new Peces(jtxtNombre.getText(), jcbHabitad.getSelectedItem().toString(), jtxtTipoAlimento.getText(),Integer.parseInt(jsAletas.getValue().toString()), jcbEsqueleto.getSelectedItem().toString());
            VerDatos.setText(VerDatos.getText() + "\n\n" + ps.MostrarDato());
            datos.add(ps);
            Limpiar();                        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbpActionPerformed
        // TODO add your handling code here:
        if(jrbp.isSelected())
        {
            jPanel1.setVisible(true);
            jPanel3.setVisible(true);
            jPanel2.setVisible(false);
        }        
    }//GEN-LAST:event_jrbpActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Registro.setVisible(true);
        Registro.setSize(1034,540);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Registro;
    private javax.swing.JTextArea VerDatos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcbEsqueleto;
    private javax.swing.JComboBox jcbHabitad;
    private javax.swing.JComboBox jcbTipoAlas;
    private javax.swing.JComboBox jcbTipoPico;
    private javax.swing.JRadioButton jrba;
    private javax.swing.JRadioButton jrbp;
    private javax.swing.JSpinner jsAletas;
    private javax.swing.JSpinner jsExtremidades;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTipoAlimento;
    // End of variables declaration//GEN-END:variables
}
